### ISSUE TITLE
Repository refactoring

### ISSUE THREAD

**Issue by obra** [keyboardio/Akela#130]
01:42 <@obra> at this point, what's in the Akela top level repo besides your example sketch and pointers
              to the other libraries?
01:42 <@obra> sorry. changing gears :)
01:42 <algernon> a few tools
01:42 <algernon> Makefile fragments, a shell script to help me flash firmware, that kind of stuff
01:43 <algernon> (another topic: colleague has his soldering kit with him today!!!)
01:43 <@obra> Could we lift that to the core KeyboardioFirmware repo and move the library submodules to 
              the Arduino-Boards?
01:43 <@obra> Awesome.
01:43 <algernon> yeah, we could
01:43 <@obra> Though actually, we may want to break out all the libraries to a Keyboardio-Libraries repo 
              and make that a submodule of Arduino-Boards.
01:43 <algernon> I'll clean it up a bit, and submit a PR
01:44 <algernon> yeah, that'd be better.
01:44 <@obra> The reason for that layer of indirection is for when we might want to support non-avr cores
01:44 <@obra> I'll create a repo
01:44 <algernon> so tools & whatnot to KeyboardioFirmware, lib links to Keyboardio-Libraries
01:45 <@obra> right. 
01:45 <algernon> can you file a bug for me, on Akela? with the above few lines pasted?
01:45 <@obra> though we should probably get Keyboardio out of the name?
01:45 <@obra> totally

**Comment by algernon** [comment]
keyboardio/KeyboardioFirmware#84 moves the rewritten tool to the core firmware. Rewrote the tool, because the makefile was a huge mess, and we used very little of make's features anyway.

This makes some parts of the script more complicated, and there are some obvious error paths unhandled at the moment, but at the same time, it becomes a little more readable, and easier to use with third-party libs. At least in my opinion.

**Comment by algernon** [comment]
Aaand done!
